version: '3'
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: ''
      POSTGRES_USER: ''
      POSTGRES_PASSWORD: ''
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
    - "7432:5432"
  app:
    build: ./server
    image: server
    container_name: server
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ''
      DOCKER_ENV: true
  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    ports:
      - "5174:80"

volumes:
  db-data: