version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: angryBeaverDB
      POSTGRES_USER: Norbert
      POSTGRES_PASSWORD: Tjtn37Aintja36FY
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
    - "7432:5432"
  app:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://Norbert:Tjtn37Aintja36FY@db/angryBeaverDB
  frontend:
    build: ./frontend
    ports:
      - "5174:80"

volumes:
  db-data: