version: '3'
services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
    - "7432:5432"
  app:
    build: ./server
    image: server
    container_name: server
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DOCKER_ENV: true
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL_DOCKER: ${VITE_API_URL_DOCKER}
    image: frontend
    container_name: frontend
    ports:
      - "5174:80"

volumes:
  db-data: